// Code generated by goctl. DO NOT EDIT.

export interface LoginReq {
	username: string
	password: string
}

export interface LoginRes {
	id: string
	name: string // 名称
	token: string
	expIn: number // 过期时间
}

export interface EntryReq {
	name: string // 名称
	desc: string // 描述
	address: string // 地址
	phone: string // 联系电话
	images: string // 图片
}

export interface StoreListReq {
	page: number
	pageSize: number
	filter: string
}

export interface StoreListRes {
	items: Array<StoreItem>
	total: number
}

export interface StoreItem {
	id: string
	name: string // 名称
	desc: string // 描述
	address: string // 地址
	phone: string // 联系电话
	images: string // 图片
}

export interface StoreDeleteReq {
	id: string
}

export interface StoreUpdateReq {
	id: string
	name: string // 名称
	desc: string // 描述
	address: string // 地址
	phone: string // 联系电话
	images: string // 图片
}

export interface GoodsListReq {
	page: number
	pageSize: number
	filter: string
}

export interface GoodsListRes {
	items: Array<GoodsItem>
	total: number
}

export interface GoodsItem {
	id: string
	name: string // 货品名
	images: string // 图片
	store: string // 商家
	desc: string // 描述
	price: number // 价格（积分）
}

export interface GoodsEntryReq {
	name: string
	images: string
	store_id: string
	desc: string
	price: number
}

export interface GoodsDeleteReq {
	id: string
}

export interface GoodsUpdateReq {
	id: string
	name: string
	images: string
	store_id: string // 商家id
	desc: string // 货品描述
	price: number
}

export interface GoodsSelectReq {
	id: string
}

export interface AddressEntryReq {
	name: string // 收货人
	phone: string // 手机号
	province: string // 省
	city: string // 市
	detail_address: string // 详细地址，到小区、街道
	full_address: string // 完整地址
	is_default: boolean // 是否为默认地址
}

export interface AddressListRes {
	address: Array<AddressItem>
}

export interface AddressItem {
	id: string // id
	name: string
	phone: string
	province: string
	city: string
	detail_address: string
	full_address: string
	is_default: boolean
}

export interface AddressDeleteReq {
	id: string
}

export interface ExpressageEntryReq {
	no: string // 快递单号
	name: string // 快递名称
	order_id: string // 订单号
}

export interface ExpressageItem {
	id: string
	no: string
	name: string
	order_id: string
	status: string // 快递状态
}

export interface ExpressageUpdateReq {
	id: string
	no: string
	name: string
}

export interface ExpressageSelectReq {
}
export interface ExpressageSelectReqParams {
}

export interface ExpenseUploadReq {
	store_name: string
	expense_at: string
	amount: number
	receipt: string
}

export interface ExpenseListRes {
	items: Array<ExpenseItem>
	total: number
}

export interface ExpenseItem {
	id: string
	user_id: string
	store_name: string
	expense_at: string
	amount: number
	receipt: string
	status: string
	remark: string
}

export interface ExpenseListReq {
	page: number
	pageSize: number
	filter: string
}

export interface ExpenseUpdateReq {
	status: string
	remark?: string // 备注
}
export interface ExpenseUpdateReqParams {
}

export interface ReceiptUploadReq {
	user_id: string
	store_name: string // 商家名称
	expense_at: string // 消费时间
	amount: number // 消费金额
	receipt: string // 票据
}

export interface AppletLoginReq {
	code: string
}

export interface AppletLoginRes {
	id: string // 用户id
	token: string
	expIn: number // 过期时间
	unionid: string
}

export interface AppletUserListReq {
	page: number
	pageSize: number
	filter: string
}

export interface AppletUserListRes {
	items: Array<AppletUserItem>
	total: number
}

export interface AppletUserItem {
	id: string
	avatar: string // 头像
	nickname: string // 昵称
	sex: string // 性别
	grade: number // 等级
	phone: string // 手机
	birthday: string // 生日
	points: number // 可用积分
}

export interface ChangeInformationReq {
	avatar: string // 头像
	nickname: string
	sex: string
	phone: string
	birthday: string
}

export interface ChangepasswordReq {
	oldpasswprd: string
	newpassword: string
}

export interface OrderEntryReq {
	address_id: string // 收货地址
	goods_id: string // 商品id
	storeId: string // 商家id
	price: number // 积分单价
	num: number // 兑换数量
	receive_way: string // 收货方式
}

export interface OrderListReq {
	page: number
	pageSize: number
	filter: string
}

export interface OrderListRes {
	total: number
	items: Array<OrderItem>
}

export interface OrderSelectRes {
	items: Array<OrderItem>
}

export interface OrderItem {
	id: string
	address: string // 收货地址
	goodsName: string // 货品名
	store: string // 商家
	price: number // 单价（积分）
	num: number // 数量
	nickname: string // 客户昵称
	receive_way: string // 收货方式
	status: string // 状态
}

export interface OrderDeleteReq {
	id: string
}

export interface OrderSignReq {
	id: string
}

export interface Response {
	points: number // 可用积分
	totalPoints: number // 总积分
}

